Version 9.5.0
## Version 9.5.0 - March 30, 2025

  - **Improved:** Document Viewer:
    - **Added:** Better multi-platform suppport. Viewing some formats requires native dependencies which we already bundled
      in our DLL for win-x64 and win-x86 platforms. In addition to these, we now also bundle dependencies for these platforms:
      - win-arm64
      - linux-x64, linux-arm64
      - osx-x64, osx-arm64
      Reference our NuGet package (not our DLL directly) especially if you are targeting linux-* and osx-*.
    - **Fixed:** Error when converting/viewing Email formats (e.g. .msg files) containing images:
      InvalidOperationException: The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
    - **Improved:** Stability and performance of Portable formats.

  - **Improved:** Updated About dialog to display Runtime Identifier, e.g. win-x64.